### ISSUE TITLE
菜单管理组件展开折叠bug【如图】

### ISSUE THREAD

**Issue by peak520** [stepui/stepin-template#14]
<img width="791" alt="1683700869407" src="https://github.com/stepui/stepin-template/assets/51201793/d520b86c-64b8-428d-9521-195785c8104e">

**Comment by peak520** [comment]
点击三级的，上面二级也关闭了！

**Comment by iczer** [comment]
已修复： 535de7fb55afc34fcba2057b3b08d0c5d4a2d3a1
