### ISSUE TITLE
iconfont 替换之后，菜单未显示图标

### ISSUE THREAD

**Issue by Sun1090** [stepui/stepin-template#27]
![c7df1e8857c462a8532c39627a053b47](https://github.com/stepui/stepin-template/assets/51160517/7f707e7b-9a36-4ce4-9522-27a52c061ad5)
![6210e06867ca5d0bb2cae94ea91511bd](https://github.com/stepui/stepin-template/assets/51160517/5be08b86-17c3-4694-abeb-ff691987a223)
<img width="574" alt="image" src="https://github.com/stepui/stepin-template/assets/51160517/57042ec4-cd8a-481a-beca-f321627b437a">

**Comment by iczer** [comment]
需要全局注册，注册及使用时名字不要带有 '-'
