### ISSUE TITLE
右上角用户下拉替换 icon 后，没有对齐

### ISSUE THREAD

**Issue by Sun1090** [stepui/stepin-template#31]
<img width="244" alt="image" src="https://github.com/stepui/stepin-template/assets/51160517/9b3c8521-52be-42cb-bf4e-1d1dde79a1e9">
<img width="557" alt="image" src="https://github.com/stepui/stepin-template/assets/51160517/443238a7-6496-40d6-bcd3-5e5db64cdaea">
图标是注册的全局 iconfont 组件，我试了菜单那是正常对齐的，右上角那歪了

**Comment by iczer** [comment]
已修复： bd748ac
