### ISSUE TITLE
布局显示有点重复

### ISSUE THREAD

**Issue by Sun1090** [stepui/stepin-template#38]
<img width="1314" alt="image" src="https://github.com/stepui/stepin-template/assets/51160517/f95c0da9-5120-4f12-bafd-dc2a9e85fd54">
首先设置项目的布局方式为 mix，然后点击头像的下拉菜单个人中心，跳转之后就显示这样了

**Comment by iczer** [comment]
已修复，升级 stepin 组件库至版本 2.1.53-beta 即可
