### ISSUE TITLE
vue-antd-admin 2.0 不继续了么？

### ISSUE THREAD

**Issue by CracKerMe** [stepui/stepin-template#4]
如题，7个多月没动静了，是遇到什么阻力了么？ 挺期待 vue-antd-admin 的 TS vue3版本的。

**Comment by iczer** [comment]
抱歉，因为个人原因，vue-antd-admin vue3 版搁置了很久。

**Comment by iczer** [comment]
抱歉，因为个人原因 vue-atnd-admin vue3 版 搁置了很久。
现在已开始继续开发维护，vue-atnd-admin vue3 版更名 stepin-template 并在此仓库管理代码
现在 v1.0.0.preview 版本已发布，感谢关注！
