### ISSUE TITLE
页面添加antd 表格，滚动条会出现在页面最下方而不是表格内部

### ISSUE THREAD

**Issue by wukai198786** [stepui/stepin-template#7]
问题：
新增一个路由菜单，在页面中添加了一个表格，columns属性如下：
const columns = [
    // {
    //   colKey: 'row-select',
    //   type: 'multiple',
    //   width: 64,
    // },
    {
      width: 180,
      dataIndex: 'plan_no',
      title: '计划编号',
      align: 'center',
    },
    {
      width: 160,
      dataIndex: 'customer_name',
      title: '客户名称',
      align: 'center',
    },
    {
      width: 280,
      dataIndex: 'location_name',
      title: '作业地点',
      align: 'center',
    },
    {
      width: 160,
      dataIndex: 'status',
      title: '计划状态',
      align: 'center',
      cell: 'status',
    },
    {
      width: 120,
      dataIndex: 'creator_name',
      title: '计划提交',
      align: 'center',
    },
    {
      width: 180,
      dataIndex: 'operator_name',
      title: '操作员',
      align: 'center',
      cell: 'operator_name',
    },
    {
      width: 140,
      dataIndex: 'assign_name',
      title: '监装员',
      align: 'center',
    },
    // {
    //   width: 210,
    //   dataIndex: 'created_at',
    //   title: '计划时间',
    //   align: 'center',
    // },
    // {
    //   width: 210,
    //   dataIndex: 'assign_date',
    //   title: '受理时间',
    //   align: 'center',
    // },
    // {
    //   width: 210,
    //   dataIndex: 'updated_at',
    //   title: '更新时间',
    //   align: 'center',
    // },
    // {
    //   width: 210,
    //   dataIndex: 'assign_date',
    //   title: '派工时间',
    //   align: 'center',
    // },
    // {
    //   width: 210,
    //   dataIndex: 'assign_date',
    //   title: '确认时间',
    //   align: 'center',
    // },
    // {
    //   width: 160,
    //   dataIndex: 'ship_name_cn',
    //   title: '中文船名',
    //   align: 'center',
    // },
    // {
    //   width: 160,
    //   dataIndex: 'ship_name_en',
    //   title: '英文船名',
    //   align: 'center',
    // },
    // {
    //   width: 120,
    //   dataIndex: 'voyage',
    //   title: '航次',
    //   align: 'center',
    // },
    // {
    //   width: 210,
    //   dataIndex: 'sail_date',
    //   title: '开航日期',
    //   align: 'center',
    // },
    // {
    //   width: 160,
    //   colKey: 'ship_type',
    //   title: '船类型',
    //   align: 'center',
    // },
    {
      width: 120,
      dataIndex: 'sign_text',
      title: '整拼标志',
      align: 'center',
    },

    {
      width: 160,
      dataIndex: 'port_code',
      title: '港口代码',
      align: 'center',
    },

    {
      dataIndex: 'action',
      title: '操作',
      width: 200,
      align: 'center',
      fixed: 'right',
    },
  ];
// template table
    <a-table
      :columns="columns"
      :data-source="dataSource"
      :pagination="pagination"
      :scroll="{ x: 4000,y:'calc(100vh - 412px)' }"
      bordered
    >
    </a-table>
滚动条出现在最下方，而不是表格内

**Comment by iczer** [comment]
已修复： 1f29b0cafecb76acc59417303016203252c5ba8b

**Comment by wukai198786** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
