### ISSUE TITLE
使用antd table 时，表格固定列头部背景透明

### ISSUE THREAD

**Issue by wukai198786** [stepui/stepin-template#9]
问题：stepin template 中使用 ant design table 表格固定列头部背景透明
代码：
  <a-table
    :columns="columns"
    :data-source="dataSource"
    :pagination="pagination"
    :loading="dataLoading"
    :scroll="{ x: 4000, y: 'calc(100vh - 412px)' }"
    bordered
  >
    <template #bodyCell="{ column, record }">
      <template v-if="column.dataIndex === 'action'">
        <a-space>
          <a-button type="primary" size="small" @click="showEditBox(record)">编辑</a-button>
          <a-button type="danger" size="small" @click="showDeleteCtn(record)">删除</a-button>
        </a-space>
      </template>
    </template>
  </a-table>

**Comment by iczer** [comment]
已修复
